# Generated by Django 4.1.2 on 2022-10-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True


    operations = [
        migrations.CreateModel(
            name="ContaCapitulos",
            fields=[
                (
                    "IdCapitulo",
                    models.CharField(max_length=1, primary_key=True, serialize=False),
                ),
                ("Denominacion", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "ContaCapitulo",
            },
        ),
    ]
