# Generated by Django 4.1.2 on 2022-10-27 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Contable", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaRubros",
            fields=[
                (
                    "IdRubro",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("Denominacion", models.CharField(max_length=30)),
                (
                    "IdCapitulo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Contable.contacapitulos",
                    ),
                ),
            ],
            options={
                "db_table": "ContaRubros",
                "unique_together": {("IdRubro", "IdCapitulo")},
            },
        ),
    ]
