# Generated by Django 4.1.2 on 2022-10-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Contable", "0004_contarubros"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contarubros",
            name="IdRubro",
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
