# Generated by Django 4.1.2 on 2022-10-28 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Contable", "0005_alter_contarubros_idrubro"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaCtaMadre",
            fields=[
                (
                    "IdCtaMadre",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("Denominacion", models.CharField(default="", max_length=50)),
                (
                    "IdRubro",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Contable.contarubros",
                    ),
                ),
            ],
            options={
                "db_table": "ContaCtaMadre",
            },
        ),
        migrations.CreateModel(
            name="ContaCuentas",
            fields=[
                (
                    "IdCuenta",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("IdCtaAuxiliar", models.CharField(default="", max_length=9)),
                ("Denominacion", models.CharField(default="", max_length=80)),
                ("Movimiento", models.BooleanField(default=True)),
                ("Saldo", models.CharField(default="", max_length=1)),
                ("Clasificacion", models.CharField(default="", max_length=1)),
                ("CodigoCorto", models.IntegerField(default=0)),
                ("SubCuenta", models.BooleanField(default=False)),
                (
                    "IdCtaMadre",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Contable.contactamadre",
                    ),
                ),
            ],
            options={
                "db_table": "ContaCuentas",
            },
        ),
    ]
